# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brewautomation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'brewautomation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62rewautomation.proto\x12\x0e\x62rewautomation\";\n\x0eTempLogRequest\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x14\n\x0c\x66\x65rmentRunId\x18\x02 \x01(\x05\x32X\n\x03\x41PI\x12Q\n\rCreateTempLog\x12\x1e.brewautomation.TempLogRequest\x1a\x1e.brewautomation.TempLogRequest\"\x00\x42\x11Z\x0f../server/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brewautomation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017../server/pb;pb'
  _globals['_TEMPLOGREQUEST']._serialized_start=40
  _globals['_TEMPLOGREQUEST']._serialized_end=99
  _globals['_API']._serialized_start=101
  _globals['_API']._serialized_end=189
# @@protoc_insertion_point(module_scope)
