# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import brewautomation_pb2 as brewautomation__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in brewautomation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTempLog = channel.unary_unary(
                '/brewautomation.API/CreateTempLog',
                request_serializer=brewautomation__pb2.TempLogRequest.SerializeToString,
                response_deserializer=brewautomation__pb2.TempLogResponse.FromString,
                _registered_method=True)
        self.GetFermentRun = channel.unary_unary(
                '/brewautomation.API/GetFermentRun',
                request_serializer=brewautomation__pb2.FermentRunGetRequest.SerializeToString,
                response_deserializer=brewautomation__pb2.FermentRunResponse.FromString,
                _registered_method=True)
        self.CreateFermentRun = channel.unary_unary(
                '/brewautomation.API/CreateFermentRun',
                request_serializer=brewautomation__pb2.FermentRunCreateRequest.SerializeToString,
                response_deserializer=brewautomation__pb2.FermentRunResponse.FromString,
                _registered_method=True)
        self.SubscribeDeviceInstruction = channel.unary_stream(
                '/brewautomation.API/SubscribeDeviceInstruction',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=brewautomation__pb2.DeviceInstruction.FromString,
                _registered_method=True)
        self.PublishDeviceInstruction = channel.unary_unary(
                '/brewautomation.API/PublishDeviceInstruction',
                request_serializer=brewautomation__pb2.DeviceInstruction.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTempLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFermentRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFermentRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeDeviceInstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishDeviceInstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTempLog': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTempLog,
                    request_deserializer=brewautomation__pb2.TempLogRequest.FromString,
                    response_serializer=brewautomation__pb2.TempLogResponse.SerializeToString,
            ),
            'GetFermentRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFermentRun,
                    request_deserializer=brewautomation__pb2.FermentRunGetRequest.FromString,
                    response_serializer=brewautomation__pb2.FermentRunResponse.SerializeToString,
            ),
            'CreateFermentRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFermentRun,
                    request_deserializer=brewautomation__pb2.FermentRunCreateRequest.FromString,
                    response_serializer=brewautomation__pb2.FermentRunResponse.SerializeToString,
            ),
            'SubscribeDeviceInstruction': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeDeviceInstruction,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=brewautomation__pb2.DeviceInstruction.SerializeToString,
            ),
            'PublishDeviceInstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishDeviceInstruction,
                    request_deserializer=brewautomation__pb2.DeviceInstruction.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brewautomation.API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brewautomation.API', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTempLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brewautomation.API/CreateTempLog',
            brewautomation__pb2.TempLogRequest.SerializeToString,
            brewautomation__pb2.TempLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFermentRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brewautomation.API/GetFermentRun',
            brewautomation__pb2.FermentRunGetRequest.SerializeToString,
            brewautomation__pb2.FermentRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFermentRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brewautomation.API/CreateFermentRun',
            brewautomation__pb2.FermentRunCreateRequest.SerializeToString,
            brewautomation__pb2.FermentRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeDeviceInstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/brewautomation.API/SubscribeDeviceInstruction',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            brewautomation__pb2.DeviceInstruction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishDeviceInstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brewautomation.API/PublishDeviceInstruction',
            brewautomation__pb2.DeviceInstruction.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
