# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brewautomation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'brewautomation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62rewautomation.proto\x12\x0e\x62rewautomation\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x07\x43ommand\x12\x13\n\x0bmessageCode\x18\x01 \x01(\x05\";\n\x0eTempLogRequest\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x14\n\x0c\x66\x65rmentRunId\x18\x02 \x01(\x05\"[\n\x0fTempLogResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x14\n\x0c\x66\x65rmentRunId\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\"\n\x14\x46\x65rmentRunGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x17\x46\x65rmentRunCreateRequest\x12\x0c\n\x04name\x18\x02 \x01(\t\".\n\x12\x46\x65rmentRunResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"3\n\x11\x44\x65viceInstruction\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x65viceId\x18\x02 \x01(\t2\xcf\x03\n\x03\x41PI\x12R\n\rCreateTempLog\x12\x1e.brewautomation.TempLogRequest\x1a\x1f.brewautomation.TempLogResponse\"\x00\x12[\n\rGetFermentRun\x12$.brewautomation.FermentRunGetRequest\x1a\".brewautomation.FermentRunResponse\"\x00\x12\x61\n\x10\x43reateFermentRun\x12\'.brewautomation.FermentRunCreateRequest\x1a\".brewautomation.FermentRunResponse\"\x00\x12[\n\x1aSubscribeDeviceInstruction\x12\x16.google.protobuf.Empty\x1a!.brewautomation.DeviceInstruction\"\x00\x30\x01\x12W\n\x18PublishDeviceInstruction\x12!.brewautomation.DeviceInstruction\x1a\x16.google.protobuf.Empty\"\x00\x42\x11Z\x0f../server/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brewautomation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017../server/pb;pb'
  _globals['_COMMAND']._serialized_start=69
  _globals['_COMMAND']._serialized_end=99
  _globals['_TEMPLOGREQUEST']._serialized_start=101
  _globals['_TEMPLOGREQUEST']._serialized_end=160
  _globals['_TEMPLOGRESPONSE']._serialized_start=162
  _globals['_TEMPLOGRESPONSE']._serialized_end=253
  _globals['_FERMENTRUNGETREQUEST']._serialized_start=255
  _globals['_FERMENTRUNGETREQUEST']._serialized_end=289
  _globals['_FERMENTRUNCREATEREQUEST']._serialized_start=291
  _globals['_FERMENTRUNCREATEREQUEST']._serialized_end=330
  _globals['_FERMENTRUNRESPONSE']._serialized_start=332
  _globals['_FERMENTRUNRESPONSE']._serialized_end=378
  _globals['_DEVICEINSTRUCTION']._serialized_start=380
  _globals['_DEVICEINSTRUCTION']._serialized_end=431
  _globals['_API']._serialized_start=434
  _globals['_API']._serialized_end=897
# @@protoc_insertion_point(module_scope)
