// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: brewautomation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TempLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature  float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	FermentRunId int32   `protobuf:"varint,2,opt,name=fermentRunId,proto3" json:"fermentRunId,omitempty"`
}

func (x *TempLogRequest) Reset() {
	*x = TempLogRequest{}
	mi := &file_brewautomation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempLogRequest) ProtoMessage() {}

func (x *TempLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brewautomation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempLogRequest.ProtoReflect.Descriptor instead.
func (*TempLogRequest) Descriptor() ([]byte, []int) {
	return file_brewautomation_proto_rawDescGZIP(), []int{0}
}

func (x *TempLogRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TempLogRequest) GetFermentRunId() int32 {
	if x != nil {
		return x.FermentRunId
	}
	return 0
}

var File_brewautomation_proto protoreflect.FileDescriptor

var file_brewautomation_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x72, 0x65, 0x77, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x72, 0x65, 0x77, 0x61, 0x75, 0x74, 0x6f,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a, 0x0e, 0x54, 0x65, 0x6d, 0x70, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65,
	0x72, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x66, 0x65, 0x72, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6e, 0x49, 0x64, 0x32, 0x58,
	0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x51, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x6d, 0x70, 0x4c, 0x6f, 0x67, 0x12, 0x1e, 0x2e, 0x62, 0x72, 0x65, 0x77, 0x61, 0x75, 0x74,
	0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x72, 0x65, 0x77, 0x61, 0x75, 0x74,
	0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_brewautomation_proto_rawDescOnce sync.Once
	file_brewautomation_proto_rawDescData = file_brewautomation_proto_rawDesc
)

func file_brewautomation_proto_rawDescGZIP() []byte {
	file_brewautomation_proto_rawDescOnce.Do(func() {
		file_brewautomation_proto_rawDescData = protoimpl.X.CompressGZIP(file_brewautomation_proto_rawDescData)
	})
	return file_brewautomation_proto_rawDescData
}

var file_brewautomation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_brewautomation_proto_goTypes = []any{
	(*TempLogRequest)(nil), // 0: brewautomation.TempLogRequest
}
var file_brewautomation_proto_depIdxs = []int32{
	0, // 0: brewautomation.API.CreateTempLog:input_type -> brewautomation.TempLogRequest
	0, // 1: brewautomation.API.CreateTempLog:output_type -> brewautomation.TempLogRequest
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brewautomation_proto_init() }
func file_brewautomation_proto_init() {
	if File_brewautomation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brewautomation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brewautomation_proto_goTypes,
		DependencyIndexes: file_brewautomation_proto_depIdxs,
		MessageInfos:      file_brewautomation_proto_msgTypes,
	}.Build()
	File_brewautomation_proto = out.File
	file_brewautomation_proto_rawDesc = nil
	file_brewautomation_proto_goTypes = nil
	file_brewautomation_proto_depIdxs = nil
}
