// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: brewautomation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_CreateTempLog_FullMethodName              = "/brewautomation.API/CreateTempLog"
	API_GetFermentRun_FullMethodName              = "/brewautomation.API/GetFermentRun"
	API_CreateFermentRun_FullMethodName           = "/brewautomation.API/CreateFermentRun"
	API_SubscribeDeviceInstruction_FullMethodName = "/brewautomation.API/SubscribeDeviceInstruction"
	API_PublishDeviceInstruction_FullMethodName   = "/brewautomation.API/PublishDeviceInstruction"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	CreateTempLog(ctx context.Context, in *TempLogRequest, opts ...grpc.CallOption) (*TempLogResponse, error)
	GetFermentRun(ctx context.Context, in *FermentRunGetRequest, opts ...grpc.CallOption) (*FermentRunResponse, error)
	CreateFermentRun(ctx context.Context, in *FermentRunCreateRequest, opts ...grpc.CallOption) (*FermentRunResponse, error)
	SubscribeDeviceInstruction(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceInstruction], error)
	PublishDeviceInstruction(ctx context.Context, in *DeviceInstruction, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateTempLog(ctx context.Context, in *TempLogRequest, opts ...grpc.CallOption) (*TempLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TempLogResponse)
	err := c.cc.Invoke(ctx, API_CreateTempLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFermentRun(ctx context.Context, in *FermentRunGetRequest, opts ...grpc.CallOption) (*FermentRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FermentRunResponse)
	err := c.cc.Invoke(ctx, API_GetFermentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateFermentRun(ctx context.Context, in *FermentRunCreateRequest, opts ...grpc.CallOption) (*FermentRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FermentRunResponse)
	err := c.cc.Invoke(ctx, API_CreateFermentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SubscribeDeviceInstruction(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceInstruction], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[0], API_SubscribeDeviceInstruction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, DeviceInstruction]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type API_SubscribeDeviceInstructionClient = grpc.ServerStreamingClient[DeviceInstruction]

func (c *aPIClient) PublishDeviceInstruction(ctx context.Context, in *DeviceInstruction, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, API_PublishDeviceInstruction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
type APIServer interface {
	CreateTempLog(context.Context, *TempLogRequest) (*TempLogResponse, error)
	GetFermentRun(context.Context, *FermentRunGetRequest) (*FermentRunResponse, error)
	CreateFermentRun(context.Context, *FermentRunCreateRequest) (*FermentRunResponse, error)
	SubscribeDeviceInstruction(*emptypb.Empty, grpc.ServerStreamingServer[DeviceInstruction]) error
	PublishDeviceInstruction(context.Context, *DeviceInstruction) (*emptypb.Empty, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) CreateTempLog(context.Context, *TempLogRequest) (*TempLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTempLog not implemented")
}
func (UnimplementedAPIServer) GetFermentRun(context.Context, *FermentRunGetRequest) (*FermentRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFermentRun not implemented")
}
func (UnimplementedAPIServer) CreateFermentRun(context.Context, *FermentRunCreateRequest) (*FermentRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFermentRun not implemented")
}
func (UnimplementedAPIServer) SubscribeDeviceInstruction(*emptypb.Empty, grpc.ServerStreamingServer[DeviceInstruction]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeDeviceInstruction not implemented")
}
func (UnimplementedAPIServer) PublishDeviceInstruction(context.Context, *DeviceInstruction) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishDeviceInstruction not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call pancis, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_CreateTempLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TempLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateTempLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_CreateTempLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateTempLog(ctx, req.(*TempLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFermentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FermentRunGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFermentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetFermentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFermentRun(ctx, req.(*FermentRunGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateFermentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FermentRunCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateFermentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_CreateFermentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateFermentRun(ctx, req.(*FermentRunCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SubscribeDeviceInstruction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).SubscribeDeviceInstruction(m, &grpc.GenericServerStream[emptypb.Empty, DeviceInstruction]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type API_SubscribeDeviceInstructionServer = grpc.ServerStreamingServer[DeviceInstruction]

func _API_PublishDeviceInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInstruction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).PublishDeviceInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_PublishDeviceInstruction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).PublishDeviceInstruction(ctx, req.(*DeviceInstruction))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brewautomation.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTempLog",
			Handler:    _API_CreateTempLog_Handler,
		},
		{
			MethodName: "GetFermentRun",
			Handler:    _API_GetFermentRun_Handler,
		},
		{
			MethodName: "CreateFermentRun",
			Handler:    _API_CreateFermentRun_Handler,
		},
		{
			MethodName: "PublishDeviceInstruction",
			Handler:    _API_PublishDeviceInstruction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDeviceInstruction",
			Handler:       _API_SubscribeDeviceInstruction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "brewautomation.proto",
}
